Resources:
  CartonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "KeySchema":
        - "AttributeName": "cartonId"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Cartons"
